WBBSE/Areas/Schools/Controllers/SchoolProfileVerificationController.cs
using System;
using System.Web;
using System.Web.Mvc;
using WBBSE.Models;
using WBBSE.Areas.Admin.Models;
using WBBSE.Areas.Schools.Models;
using ViewModel;
using Common;
using System.Web.Routing;

namespace WBBSE.Areas.Schools.Controllers
{
    /*******************************************************************************
    * A BRIEF HISTORY OF SchoolProfileVerificationController.
    * CONTAINS SCHOOL PROFILE VERIFICATION DATA RELATED ACTIONS 
    * COMMON: COMMON PROJECT FOR UTILITY FUNCTIONS
    * ViewModel: THIS IS A PROJECT WHERE ALL VIEW MODEL CLASSES ARE WRITTEN AS CLASS FILE.
    * WBBSE.MODELS: COMMON MODEL CLASS FOR COMMON ACTION/FUNCTIONS LIKE EXCEPTION LOG.  
    * WBBSE.AREAS.SCHOOLS.MODELS: MODEL CLASS FOR SchoolHome RELATED BUSINESS LOGICS & FUNCTIONS. 
    ******************************************************************************/

    /* ROLE BASED ASP.NET MVC AUTHORIZATION [ONLY SCHOOL ROLE IS ALLOWED FOR ACCESSING THIS CONTROLLER]
     * NoCache: PREVENT CACHING IN MVC
     */
    [Authorize(Roles = UserType.SCHOOL), NoCache]
    public class SchoolProfileVerificationController : Controller
    {        
        public ActionResult SchoolProfileVerification() //DEFAULT ACTION OF THIS CONTROLLER
        {
            try
            {
                if (Session[SessionNames.NewPasswordChangedYN].ToString() == "Y") //IF ALREADY CHANGED THE PASSWORD THEN REDIRECT TO SCHOOL HOME PAGE VIEW
                {
                    return RedirectToActionPermanent("SchoolHome", "SchoolHome");
                }

                int err = 0;
                string resendEmailOTPYN = string.Empty, resendContactOTPYN = string.Empty, showHomeLinkYN = string.Empty;
                VMProfileVerification data = new VMProfileVerification();
                int userId = (Session[SessionNames.UserId] == null) ? 0 : Convert.ToInt32(Session[SessionNames.UserId]); //USER UNIQUE ID
                int userTypeId = Convert.ToInt32(Session[SessionNames.UserTypeId]); //USER TYPE UNIQUE ID
                int groupId = (Session[SessionNames.GroupId] == null) ? -1 : Convert.ToInt32(Session[SessionNames.GroupId]); // USER GROUP UNIQUE ID
                Int64 organizationId = Convert.ToInt64(Session[SessionNames.OrganizationId]); //SCHOOL UNIQUE ID

                /*CALLING THE MODEL FOR SCHOOL PROFILE VERIFICATION DATA*/
                data = new MSchoolProfileVerification().getOrganizationProfileVerificationData(ref err, userId, ref resendEmailOTPYN, ref resendContactOTPYN, ref showHomeLinkYN, userTypeId, organizationId, groupId, (TempData[TempDataNames.ProfileVerificationDataFetchMode] == null) ? ProfileVerificationDataFetchMode.New : TempData[TempDataNames.ProfileVerificationDataFetchMode].ToString());

                if (err == 0) //SUCCESS AND SETTING THE RESPECTIVE VIEW DATA
                {
                    ViewData[ViewDataNames.EmailOTPVisibleYN] = resendEmailOTPYN;
                    ViewData[ViewDataNames.ContactOTPVisibleYN] = resendContactOTPYN;
                    ViewData[ViewDataNames.ShowHomeLinksYN] = showHomeLinkYN;
                }
                if (TempData[TempDataNames.SaveStatus] == null) //CONFIGURATION FOR ERROR & SUCCESS MESSAGE VISIBILITY
                {
                    ViewData[ViewDataNames.ErrorVisibility] = "none";
                    ViewData[ViewDataNames.SucessVisibility] = "none";
                }
                else if (TempData[TempDataNames.SaveStatus].ToString() == "SP") //PASSWORD SAVE SUCCESS
                {
                    ViewData[ViewDataNames.ErrorVisibility] = "none";
                    ViewData[ViewDataNames.SucessVisibility] = "";
                    ViewData[ViewDataNames.SaveInfo] = Message.ProfileVerification.SchoolProfileVerificationDataSaveMsg;
                }
                else if (TempData[TempDataNames.SaveStatus].ToString() == "SEG") //EMAIL SEND OTP SUCCESS
                {
                    ViewData[ViewDataNames.ErrorVisibility] = "none";
                    ViewData[ViewDataNames.SucessVisibility] = "";
                    ViewData[ViewDataNames.SaveInfo] = Message.ProfileVerification.EmailVerificationOTPSent;
                    ViewData[ViewDataNames.EmailOTPVisibleYN] = "Y";
                }
                else if (TempData[TempDataNames.SaveStatus].ToString() == "SER") //EMAIL RESEND OTP SUCCESS
                {
                    ViewData[ViewDataNames.ErrorVisibility] = "none";
                    ViewData[ViewDataNames.SucessVisibility] = "";
                    ViewData[ViewDataNames.SaveInfo] = Message.ProfileVerification.EmailVerificationOTPSent;
                    ViewData[ViewDataNames.EmailOTPVisibleYN] = "Y";
                }
                else if (TempData[TempDataNames.SaveStatus].ToString() == "SEC") //EMAIL OTP CONFIRMATION SUCCESS
                {
                    ViewData[ViewDataNames.ErrorVisibility] = "none";
                    ViewData[ViewDataNames.SucessVisibility] = "";
                    ViewData[ViewDataNames.SaveInfo] = Message.ProfileVerification.EmailVerificationSaveMsg;
                }
                else if (TempData[TempDataNames.SaveStatus].ToString() == "SCG") //CONTACT SEND OTP SUCCESS
                {
                    ViewData[ViewDataNames.ErrorVisibility] = "none";
                    ViewData[ViewDataNames.SucessVisibility] = "";
                    ViewData[ViewDataNames.SaveInfo] = Message.ProfileVerification.ContactNoVerificationOTPSent;
                    ViewData[ViewDataNames.ContactOTPVisibleYN] = "Y";
                }
                else if (TempData[TempDataNames.SaveStatus].ToString() == "SCR") //CONTACT RESEND OTP SUCCESS
                {
                    ViewData[ViewDataNames.ErrorVisibility] = "none";
                    ViewData[ViewDataNames.SucessVisibility] = "";
                    ViewData[ViewDataNames.SaveInfo] = Message.ProfileVerification.ContactNoVerificationOTPSent;
                    ViewData[ViewDataNames.ContactOTPVisibleYN] = "Y";
                }
                else if (TempData[TempDataNames.SaveStatus].ToString() == "SCC") //CONTACT OTP CONFIRMATION SUCCESS
                {
                    ViewData[ViewDataNames.ErrorVisibility] = "none";
                    ViewData[ViewDataNames.SucessVisibility] = "";
                    ViewData[ViewDataNames.SaveInfo] = Message.ProfileVerification.ContactNoVerificationSaveMsg;
                }
                else if (TempData[TempDataNames.SaveStatus].ToString() == "FP") //PASSWORD SAVE FAILURE
                {
                    ViewData[ViewDataNames.ErrorVisibility] = "";
                    ViewData[ViewDataNames.SucessVisibility] = "none";
                    ViewData[ViewDataNames.SaveInfo] = Message.ErrorMsg;
                }
                else if (TempData[TempDataNames.SaveStatus].ToString() == "FEG") //EMAIL SEND OTP FAILURE
                {
                    ViewData[ViewDataNames.ErrorVisibility] = "";
                    ViewData[ViewDataNames.SucessVisibility] = "none";
                    ViewData[ViewDataNames.SaveInfo] = Message.ProfileVerification.EmailVerificationOTPSentFailed;
                }
                else if (TempData[TempDataNames.SaveStatus].ToString() == "FER") //EMAIL RESEND OTP FAILURE
                {
                    ViewData[ViewDataNames.ErrorVisibility] = "";
                    ViewData[ViewDataNames.SucessVisibility] = "none";
                    ViewData[ViewDataNames.SaveInfo] = Message.ProfileVerification.EmailVerificationOTPSentFailed;
                }
                else if (TempData[TempDataNames.SaveStatus].ToString() == "FEC") //EMAIL OTP CONFIRMATION FAILURE
                {
                    ViewData[ViewDataNames.ErrorVisibility] = "";
                    ViewData[ViewDataNames.SucessVisibility] = "none";
                    ViewData[ViewDataNames.SaveInfo] = Message.ProfileVerification.EmailVerificationErrorMsg;
                }
                else if (TempData[TempDataNames.SaveStatus].ToString() == "FCG") //CONTACT SEND OTP FAILURE
                {
                    ViewData[ViewDataNames.ErrorVisibility] = "";
                    ViewData[ViewDataNames.SucessVisibility] = "none";
                    ViewData[ViewDataNames.SaveInfo] = Message.ProfileVerification.ContactNoVerificationOTPSentFailed;
                }
                else if (TempData[TempDataNames.SaveStatus].ToString() == "FCR") //CONTACT RESEND OTP FAILURE
                {
                    ViewData[ViewDataNames.ErrorVisibility] = "";
                    ViewData[ViewDataNames.SucessVisibility] = "none";
                    ViewData[ViewDataNames.SaveInfo] = Message.ProfileVerification.ContactNoVerificationOTPSentFailed;
                }
                else if (TempData[TempDataNames.SaveStatus].ToString() == "FCC") //CONTACT OTP CONFIRMATION FAILURE
                {
                    ViewData[ViewDataNames.ErrorVisibility] = "";
                    ViewData[ViewDataNames.SucessVisibility] = "none";
                    ViewData[ViewDataNames.SaveInfo] = Message.ProfileVerification.ContactNoVerificationErrorMsg;
                }
                //SHOW HOME BUTTON LINK
                if (Session[SessionNames.NewPasswordChangedYN].ToString() == "Y" && (Session[SessionNames.EmailVerifiedYN].ToString() == "Y" || Session[SessionNames.ContactNoVerifiedYN].ToString() == "Y"))
                {
                    ViewData[ViewDataNames.ShowHomeLinksYN] = "Y";
                }
                return View(data);
            }
            catch (Exception ex)
            {
                /********HANDLEING CATCH EXCEPTION LOG USING COMMON EXCEPTION HANDLING & ERROR VIEW PAGE REDIRECTION *****************/
                MCommon.saveExceptionLog(ex.Message, "SchoolProfileVerification/View", "SchoolProfileVerificationController");
                return Redirect("~/Error/Unexpected.html");
            }
        }

WBBSE/Areas/Schools/Views/SchoolProfileVerification/EmailVerification.cshtml
@model ViewModel.VMProfileVerification
@using Common;

@{
    ViewBag.Title = "WBBSE School :: School Email Verification";
    Layout = "~/Areas/Schools/Views/Shared/_LayoutSchool.cshtml";
}

@section htmlhead
{
    <link href="~/css/main.css" rel="stylesheet" />
}

@section pageheader
{
    <h1 class="h3 font-weight-bold text-info text-uppercase mb-1 pb-2">
        School Email Verification
    </h1>
    <hr class="pb-2" />
}

@section info
{
    <div id="divE" class="alert alert-danger alert-dismissible" style="color:#721c24;background-color:#f8d7da;border-color:#f5c6cb;display:@ViewData[ViewDataNames.ErrorVisibility];">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <ul style="list-style-type: none;">
            <li>
                @Html.Raw(ViewData[ViewDataNames.SaveInfo])
            </li>
        </ul>
    </div>
    <div id="divS" class="alert alert-success alert-dismissible" style="color:#155724;background-color:#d4edda;border-color#c3e6cb;display:@ViewData[ViewDataNames.SucessVisibility]">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <ul style="list-style-type: none;">
            <li>
                @ViewData[ViewDataNames.SaveInfo]
            </li>
        </ul>
    </div>
}

<!--Loader-->
<div id="preloader">
    <div id="loader"></div>
</div>

<div class="custom-div-center">
    @using (Html.BeginForm("EmailVerification", "SchoolProfileVerification", FormMethod.Post, new { @autocomplete = "off" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div class="row" style="margin-bottom: 10px;">
            <div class="col-md-12 text-center">
                Verify Email Address <hr />
            </div>
        </div>
        <div class="row" style="margin-bottom: 10px;">
            <div class="col-sm-3" style="text-align: right;">Email Id <span style="color: red;">*</span></div>
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.EMailId, new { @id = "txtEmailId", @class = "form-control allowCharForEmailId", @placeholder = "Email Id *", @maxlength = 100, @oninput = "javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);" })
            </div>
            <div class="col-sm-3">
                <button type="submit" id="btnGetOTPEmailId" class="btn btn-outline-info">Get OTP</button>
                @if (ViewData[ViewDataNames.EmailOTPVisibleYN] == "Y")
                {
                    <button type="submit" id="btnResendOTPEmailId" title="Resend OTP" class="btn-link" style="margin-left: 5px;" onclick="return resendOTPE()">Resend OTP</button>
                }
            </div>
        </div>
        if (@ViewData[ViewDataNames.EmailOTPVisibleYN] == "Y")
        {
            <div class="row" style="margin-bottom: 10px;">
                <div class="col-sm-3" style="text-align: right;">Confirm OTP <span style="color: red;">*</span></div>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.OTP, new { @class = "form-control checkContactNo", @id = "txtOTPEmailId", @placeholder = "Enter OTP", @maxlength = 6, @oninput = "javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);" })
                </div>
                <div class="col-sm-3">
                    <button type="submit" id="btnSaveEmailId" class="btn btn-primary" onclick="return saveOTPE()">Confirm</button>
                </div>
            </div>
        }
        <div class="row" id="divEInfo" style="display: none;">
            <div class="col-sm-3"></div>
            <div class="col-sm-6 text-center">
                <div class="alert alert-danger" style="padding: 10px;color:#721c24;background-color:#f8d7da;border-color:#f5c6cb;">
                    <button type="button" class="close" id="btnEClose">×</button>
                    <span id="InfoE"></span>
                </div>
            </div>
        </div>
        @Html.HiddenFor(m => m.OperationType, new { @id = "he" })
    }
</div>

@section scripts
{
    <script src="~/Areas/Schools/js/email-verification.js?v=@DateTime.Now.ToFileTime().ToString()"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            HideLoader();

            //anchor active
            var activeLink = "@ViewData[ViewDataNames.ActiveLinkA]";
            var currentA = document.getElementById(activeLink);
            currentA.classList.add("active");
            //anchor div
            var activeDIV = currentA.parentElement.parentElement.id;
            var currentDIV = document.getElementById(activeDIV);
            currentDIV.classList.add("show");
            //anchor li
            var activeLI = currentA.parentElement.parentElement.parentElement.id;
            var currentLI = document.getElementById(activeLI);
            currentLI.classList.add("active");
        });
    </script>
}